# Generated by Django 2.2.2 on 2020-04-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_area', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
